const CREATE_UPLOADED_FILE = 'CreateUploadedFile';
const GET_UPLOADED_FILE_BY_ID = 'GetUploadedFileById';
const REMOVE_UPLOADED_FILE_BY_ID = 'RemoveUploadedFileById';
const UPDATE_UPLOADED_FILE_BY_ID = 'UpdateUploadedFileById';
const GET_UPLOADED_FILES = 'GetUploadedFiles';
module.exports = { CREATE_UPLOADED_FILE, GET_UPLOADED_FILE_BY_ID, REMOVE_UPLOADED_FILE_BY_ID, UPDATE_UPLOADED_FILE_BY_ID, GET_UPLOADED_FILES };