const CREATE_UPLOADED_FILE = 'CreateUploadedFile';
const GET_UPLOADED_FILE_BY_ID = 'GetUploadedFileById';
const REMOVE_UPLOADED_FILE = 'RemoveUploadedFile';
const UPDATE_UPLOADED_FILE_BY_ID = 'UpdateUploadedFileById';

module.exports = { CREATE_UPLOADED_FILE, GET_UPLOADED_FILE_BY_ID, REMOVE_UPLOADED_FILE, UPDATE_UPLOADED_FILE_BY_ID };