const CREATE_UPLOADED_FILE_CONTENT = 'CreateUploadedFileContent';
const GET_UPLOADED_FILE_CONTENT_BY_ID = 'GetUploadedFileContentById';
const REMOVE_UPLOADED_FILE_CONTENT_BY_ID = 'RemoveUploadedFileContentById';
const UPDATE_UPLOADED_FILE_CONTENT_BY_ID = 'UpdateUploadedFileContentById';

module.exports = {
    CREATE_UPLOADED_FILE_CONTENT,
    GET_UPLOADED_FILE_CONTENT_BY_ID,
    REMOVE_UPLOADED_FILE_CONTENT_BY_ID,
    UPDATE_UPLOADED_FILE_CONTENT_BY_ID
}